---
version: 2
multicolumn: false
web-width: 600px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/screenshot3/screenshot.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/872680/articles/1253170/master/folder/figures/screenshot3"
    url: "/users/872680/articles/1253170/master/file/figures/screenshot3/screenshot.png"
